--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iSrDxv/Practice-StromMC
build-by-default: true
branches:
- stable
projects:
  Practice-StromMC:
    path: ""
    libs:
      - src: ScoreboardLib
        branch: stable
        version: ^2.0.0
      - src: ExodusDevs/TrabslationAPI
        version: ^2.0.0
      - src: ExodusDevs/WorldBackupLib
        version: ^2.0.0
      - src: poggit/libasynql/libasynql
        version: ^4.1.6
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.1.0
...