--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iSrDxv/Practice-StromMC
build-by-default: true
branches:
- stable
projects:
  Practice-StromMC:
    path: ""
    lint:
     phpstan: false
    libs:
      - src: isrdxv/scoreboard
        version: ^2.0.0
      - src: poggit/libasynql/libasynql
        version: ^4.1.6
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.1.0
      - src: CortexPE/Commando/Commando
        version: ^3.1.0
...