--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iSrDxv/Practice-StromMC
build-by-default: true
branches:
- stable
projects:
  Practice-StromMC:
    path: ""
    libs:
      - src: isrdxv/ScoreboardLib
        version: ^2.0.0
      - src: ExodusDevs/TrabslationAPI
        version: ^2.0.0
      - src: ExodusDevs/WorldBackupLib
        version: ^2.0.0
...