--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iSrDxv/Practice-StromMC
build-by-default: true
branches:
- stable
projects:
  Practice-StromMC:
    path: ""
    lint:
     phpstan: false
    libs:
      - src: ExodusDevs/WorldBackupLib/WorldBackupLib
        version: ^2.0.0
      - src: ExodusDevs/Scoreboard/Scoreboard
        version: ^1.0.1
      - src: ExodusDevs/TranslationAPI/Translation
        branch: master
        version: ^1.0.8
      - src: ExodusDevs/Cache/Cache
        version: ^1.1
      - src: poggit/libasynql/libasynql
        version: ^4.1.6
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.1.0
      - src: LatamPMDevs/Commando/Commando
        branch: pm5
        version: ^3.1.1
...
