# Season System
# Format Time: Y-m-d H:i:s
season-start: "2024-02-21 15:16:17"
season-end: "2024-02-30 15:16:17"

# Set maintenance mode
maintenance: false

# Database config
database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: sqlite.db
  # Edit these settings only if you choose "mysql".
  mysql:
    host: localhost
    # Avoid using the "root" user for security reasons.
    username: root
    password: root
    schema: strom
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1
